resources:
  - deployment.yml
  - service.yml

commonLabels:
  app: httpenv

nameSuffix: -v1

configMapGenerator:
  - name: httpenv-cm
    literals:
      - BG_COLOR=#12181b
      - FONT_COLOR=#FFFFFF
      - CUSTOM_HEADER=My Custom Message
